# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tf <- function(y, l, D, P, n, k, e, tau) {
    .Call('btf_tf', PACKAGE = 'btf', y, l, D, P, n, k, e, tau)
}

