# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tf_approx <- function(y, l, D, k, eps, tau, max_iter) {
    .Call('btf_tf_approx', PACKAGE = 'btf', y, l, D, k, eps, tau, max_iter)
}

